--
-- PostgreSQL database dump
--

\restrict VO0fWIi4N5JBcbyGSgGBHQcIO2aETM6Y7Kb2843IL028cmSSkOgj381D1pe6oDL

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-03 23:47:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16398)
-- Name: Financial; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA "Financial";


ALTER SCHEMA "Financial" OWNER TO pg_database_owner;

--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA "Financial"; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA "Financial" IS 'Financial app schema';


--
-- TOC entry 221 (class 1255 OID 16409)
-- Name: set_modified_date(); Type: FUNCTION; Schema: Financial; Owner: postgres
--

CREATE FUNCTION "Financial".set_modified_date() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW."Modified Date" := now();
  RETURN NEW;
END $$;


ALTER FUNCTION "Financial".set_modified_date() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16388)
-- Name: Financial Notes; Type: TABLE; Schema: Financial; Owner: postgres
--

CREATE TABLE "Financial"."Financial Notes" (
    "ID" integer NOT NULL,
    "Expense" text NOT NULL,
    "Spend" numeric(14,2) NOT NULL,
    "Source" text NOT NULL,
    "Balance Due" numeric(14,2),
    notes text,
    flag boolean DEFAULT false NOT NULL,
    "Created Date" timestamp with time zone DEFAULT now() NOT NULL,
    "Modified Date" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE "Financial"."Financial Notes" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16399)
-- Name: Financial Notes_ID_seq; Type: SEQUENCE; Schema: Financial; Owner: postgres
--

ALTER TABLE "Financial"."Financial Notes" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Financial"."Financial Notes_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: incoming_sources; Type: TABLE; Schema: Financial; Owner: postgres
--

CREATE TABLE "Financial".incoming_sources (
);


ALTER TABLE "Financial".incoming_sources OWNER TO postgres;

--
-- TOC entry 4852 (class 0 OID 16388)
-- Dependencies: 218
-- Data for Name: Financial Notes; Type: TABLE DATA; Schema: Financial; Owner: postgres
--

COPY "Financial"."Financial Notes" ("ID", "Expense", "Spend", "Source", "Balance Due", notes, flag, "Created Date", "Modified Date") FROM stdin;
1	Electricity bill	180.00	PJ Foods	0.00	paid for August 2025	t	2025-09-25 20:40:46.416707-04	2025-09-25 20:40:46.416707-04
\.


--
-- TOC entry 4853 (class 0 OID 16395)
-- Dependencies: 219
-- Data for Name: incoming_sources; Type: TABLE DATA; Schema: Financial; Owner: postgres
--

COPY "Financial".incoming_sources  FROM stdin;
\.


--
-- TOC entry 4862 (class 0 OID 0)
-- Dependencies: 220
-- Name: Financial Notes_ID_seq; Type: SEQUENCE SET; Schema: Financial; Owner: postgres
--

SELECT pg_catalog.setval('"Financial"."Financial Notes_ID_seq"', 1, true);


--
-- TOC entry 4705 (class 2606 OID 16392)
-- Name: Financial Notes Financial Notes_pkey; Type: CONSTRAINT; Schema: Financial; Owner: postgres
--

ALTER TABLE ONLY "Financial"."Financial Notes"
    ADD CONSTRAINT "Financial Notes_pkey" PRIMARY KEY ("ID");


--
-- TOC entry 4706 (class 2620 OID 16410)
-- Name: Financial Notes trg_set_modified_date; Type: TRIGGER; Schema: Financial; Owner: postgres
--

CREATE TRIGGER trg_set_modified_date BEFORE UPDATE ON "Financial"."Financial Notes" FOR EACH ROW EXECUTE FUNCTION "Financial".set_modified_date();


--
-- TOC entry 4861 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA "Financial"; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA "Financial" TO PUBLIC;


-- Completed on 2025-10-03 23:47:31

--
-- PostgreSQL database dump complete
--

\unrestrict VO0fWIi4N5JBcbyGSgGBHQcIO2aETM6Y7Kb2843IL028cmSSkOgj381D1pe6oDL

